/**
 * Cross-references vscode-extension/src/providers/completion-data.ts (the
 * vscode-extension's own hand-maintained completion data -- deliberately
 * split out of completion.ts with no `vscode` import so it's importable
 * here) against the real schemas it's supposed to mirror.
 *
 * Unlike HANDLER_METADATA (auto-generated by scripts/extract-metadata.ts
 * from the real handler schemas -- see extension-assets.ts), the ROUTE_
 * PROPERTIES/MATCH_PROPERTIES lists here are hand-typed and can silently
 * drift from CaddyRouteSchema/CaddyRouteMatcherSchema. That's exactly what
 * had happened: MATCH_PROPERTIES was missing path_regexp, header_regexp,
 * client_ip, and tls entirely (no autocomplete offered for four real,
 * already-validated matchers), found while building this test.
 */
import { describe, test, expect } from "vitest";
import {
  CaddyRouteSchema,
  CaddyRouteMatcherSchema,
  ReverseProxyHandlerSchema,
} from "../schemas.js";
import {
  ROUTE_PROPERTIES,
  MATCH_PROPERTIES,
  ENUM_VALUES,
} from "../../vscode-extension/src/providers/completion-data.js";

describe("completion-data.ts stays in sync with the real schemas", () => {
  test("ROUTE_PROPERTIES matches CaddyRouteSchema's real keys exactly", () => {
    const completionNames = ROUTE_PROPERTIES.map((p) => p.name).sort();
    const schemaNames = Object.keys(CaddyRouteSchema.shape).sort();

    expect(
      completionNames,
      "vscode-extension's ROUTE_PROPERTIES completion list doesn't match CaddyRouteSchema " +
        "(src/schemas.ts) -- update vscode-extension/src/providers/completion-data.ts."
    ).toEqual(schemaNames);
  });

  test("MATCH_PROPERTIES matches CaddyRouteMatcherSchema's real keys exactly", () => {
    const completionNames = MATCH_PROPERTIES.map((p) => p.name).sort();
    const schemaNames = Object.keys(CaddyRouteMatcherSchema.shape).sort();

    expect(
      completionNames,
      "vscode-extension's MATCH_PROPERTIES completion list doesn't match " +
        "CaddyRouteMatcherSchema (src/schemas.ts) -- update " +
        "vscode-extension/src/providers/completion-data.ts. This is exactly the class of bug " +
        "that left path_regexp/header_regexp/client_ip/tls with no autocomplete despite being " +
        "real, validated matchers."
    ).toEqual(schemaNames);
  });

  test("ENUM_VALUES.selection_policy matches the real reverse_proxy selection policy enum", () => {
    const loadBalancing = ReverseProxyHandlerSchema.shape.load_balancing.unwrap();
    const selectionPolicy = loadBalancing.shape.selection_policy.unwrap();
    const realValues = [...selectionPolicy.shape.policy.options].sort();

    const completionValues = ENUM_VALUES.selection_policy.map((v) => v.value).sort();

    expect(
      completionValues,
      "ENUM_VALUES.selection_policy (completion-data.ts) doesn't match the real " +
        "policy enum on ReverseProxyHandlerSchema.load_balancing.selection_policy.policy."
    ).toEqual(realValues);
  });

  // HTTP_METHODS and ENUM_VALUES.protocol/encodings are intentionally NOT
  // checked here: HttpMethodSchema and matchProtocolSchema are both plain
  // z.string() (real Caddy accepts any method/protocol string -- see their
  // doc comments), and `encodings` is a passthrough record, so none of
  // these has a real schema-level enum to diff against. They're curated
  // "common values" suggestion lists by design, not an exhaustive/enforced
  // set -- see HTTP_METHODS's own doc comment in completion-data.ts.
});
